using Codebase;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using UnityEngine;

namespace oomtm450PuckMod_Ruleset {
    internal static class PenaltyModule {
        #region Constants
        internal const int LONG_PENALTY_TIME_MS = 45000;
        internal const int SHORT_PENALTY_TIME_MS = 30000;

        private static readonly Vector3 BLUE_PENALTY_BOX_POSITION_DEFAULT = new Vector3(26f, 0.9f, 1.5f); // TODO : Config.
        private static Vector3 BLUE_PENALTY_BOX_POSITION { get; set; }

        private static Vector3 RED_PENALTY_BOX_POSITION { get; set; }

        private static readonly Vector3 INFRONT_BLUE_PENALTY_BOX_POSITION_DEFAULT = new Vector3(21.8f, 0.05f, 1.5f); // TODO : Config.
        private static Vector3 INFRONT_BLUE_PENALTY_BOX_POSITION { get; set; }

        private static Vector3 INFRONT_RED_PENALTY_BOX_POSITION { get; set; }

        private static readonly Quaternion PENALTY_ROTATION = Quaternion.Euler(0f, 270f, 0f); // TODO : Config.

        private static readonly Vector3 DELAY_OF_GAME_POSITION_DEFAULT = new Vector3(22.74f, -0.22f, 46.04f); // TODO : Config.
        private static Vector3 DELAY_OF_GAME_POSITION { get; set; }

        private static readonly Vector3 DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1_DEFAULT = new Vector3(19.45f, 0f, 43.8f); // TODO : Config.
        private static Vector3 DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1 { get; set; }

        private static readonly Vector3 DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2_DEFAULT = new Vector3(23.20f, 0f, 33.7f); // TODO : Config.
        private static Vector3 DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2 { get; set; }

        private static Vector3 DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_1 { get; set; }
        private static Vector3 DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_2 { get; set; }

        private static Vector3 DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_1 { get; set; }
        private static Vector3 DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_2 { get; set; }

        private static Vector3 DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_1 { get; set; }
        private static Vector3 DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_2 { get; set; }

        private static readonly Vector3 DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1_DEFAULT = new Vector3(15.55f, 0f, 45.3f); // TODO : Config.
        private static Vector3 DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1 { get; set; }

        private static readonly Vector3 DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2_DEFAULT = new Vector3(21.65f, 0f, 39.15f); // TODO : Config.
        private static Vector3 DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2 { get; set; }

        private static Vector3 DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_1 { get; set; }
        private static Vector3 DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_2 { get; set; }

        private static Vector3 DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_1 { get; set; }
        private static Vector3 DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_2 { get; set; }

        private static Vector3 DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_1 { get; set; }
        private static Vector3 DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_2 { get; set; }

        private static readonly Dictionary<string, bool> POSITION_IS_PENALIZED_DEFAULT = new Dictionary<string, bool> {
            { Codebase.PlayerFunc.GOALIE_POSITION, false },
            { Codebase.PlayerFunc.CENTER_POSITION, false },
            { Codebase.PlayerFunc.LEFT_WINGER_POSITION, false },
            { Codebase.PlayerFunc.RIGHT_WINGER_POSITION, false },
            { Codebase.PlayerFunc.LEFT_DEFENDER_POSITION, false },
            { Codebase.PlayerFunc.RIGHT_DEFENDER_POSITION, false },
        };

        private static readonly Dictionary<int, bool> PENALTY_BENCH_POSITION_DEFAULT = new Dictionary<int, bool> {
            { 0, false },
            { 1, false },
            { 2, false },
        };
        #endregion

        #region Properties
        internal static LockDictionary<string, LockList<Penalty>> PenalizedPlayers { get; } = new LockDictionary<string, LockList<Penalty>>();

        internal static int PenalizedPlayersCountBlueTeam { get; set; } = 0;

        internal static int PenalizedPlayersInBoxCountBlueTeam { get; set; } = 0;

        internal static int PenalizedPlayersCountRedTeam { get; set; } = 0;

        internal static int PenalizedPlayersInBoxCountRedTeam { get; set; } = 0;

        internal static LockDictionary<PlayerTeam, bool> PenaltyToBeCalled { get; } = new LockDictionary<PlayerTeam, bool> {
            { PlayerTeam.Blue, false },
            { PlayerTeam.Red, false },
        };

        internal static LockDictionary<PlayerTeam, LockDictionary<string, bool>> PositionIsPenalized { get; } = new LockDictionary<PlayerTeam, LockDictionary<string, bool>> {
            { PlayerTeam.Blue, new LockDictionary<string, bool>(POSITION_IS_PENALIZED_DEFAULT) },
            { PlayerTeam.Red, new LockDictionary<string, bool>(POSITION_IS_PENALIZED_DEFAULT) },
        };

        internal static LockDictionary<PlayerTeam, LockDictionary<int, bool>> PenaltyBenchPositionIsOccupied { get; } = new LockDictionary<PlayerTeam, LockDictionary<int, bool>> {
            { PlayerTeam.Blue, new LockDictionary<int, bool>(PENALTY_BENCH_POSITION_DEFAULT) },
            { PlayerTeam.Red, new LockDictionary<int, bool>(PENALTY_BENCH_POSITION_DEFAULT) },
        };

        internal static PenaltyType LastPenaltyCalled { get; set; }
        #endregion

        #region Methods/Functions
        internal static void ResetCoordinates() {
            BLUE_PENALTY_BOX_POSITION = new Vector3(BLUE_PENALTY_BOX_POSITION_DEFAULT.x, BLUE_PENALTY_BOX_POSITION_DEFAULT.y, BLUE_PENALTY_BOX_POSITION_DEFAULT.z);
            RED_PENALTY_BOX_POSITION = new Vector3(BLUE_PENALTY_BOX_POSITION.x, BLUE_PENALTY_BOX_POSITION.y, BLUE_PENALTY_BOX_POSITION.z * -1);

            INFRONT_BLUE_PENALTY_BOX_POSITION = new Vector3(INFRONT_BLUE_PENALTY_BOX_POSITION_DEFAULT.x, INFRONT_BLUE_PENALTY_BOX_POSITION_DEFAULT.y, INFRONT_BLUE_PENALTY_BOX_POSITION_DEFAULT.z);
            INFRONT_RED_PENALTY_BOX_POSITION = new Vector3(INFRONT_BLUE_PENALTY_BOX_POSITION.x, INFRONT_BLUE_PENALTY_BOX_POSITION.y, INFRONT_BLUE_PENALTY_BOX_POSITION.z * -1);

            DELAY_OF_GAME_POSITION = new Vector3(DELAY_OF_GAME_POSITION_DEFAULT.x, DELAY_OF_GAME_POSITION_DEFAULT.y, DELAY_OF_GAME_POSITION_DEFAULT.z);

            DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1_DEFAULT.x, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1_DEFAULT.y, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1_DEFAULT.z);
            DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2_DEFAULT.x, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2_DEFAULT.y, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2_DEFAULT.z);

            DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1.x, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1.y, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1.z * -1);
            DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2.x, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2.y, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2.z * -1);

            DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1.x * -1, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1.y, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1.z);
            DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2.x * -1, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2.y, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2.z);

            DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1.x * -1, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1.y, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1.z * -1);
            DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2.x * -1, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2.y, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2.z * -1);

            DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1_DEFAULT.x, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1_DEFAULT.y, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1_DEFAULT.z);
            DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2_DEFAULT.x, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2_DEFAULT.y, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2_DEFAULT.z);

            DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1.x, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1.y, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1.z * -1);
            DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2.x, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2.y, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2.z * -1);

            DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1.x * -1, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1.y, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1.z);
            DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2.x * -1, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2.y, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2.z);

            DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1.x * -1, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1.y, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1.z * -1);
            DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2.x * -1, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2.y, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2.z * -1);
        }

        internal static void ScaleXCoordinates(float arenaScaleX) {
            BLUE_PENALTY_BOX_POSITION = new Vector3(BLUE_PENALTY_BOX_POSITION.x * arenaScaleX, BLUE_PENALTY_BOX_POSITION.y, BLUE_PENALTY_BOX_POSITION.z);
            RED_PENALTY_BOX_POSITION = new Vector3(RED_PENALTY_BOX_POSITION.x * arenaScaleX, RED_PENALTY_BOX_POSITION.y, RED_PENALTY_BOX_POSITION.z);

            INFRONT_BLUE_PENALTY_BOX_POSITION = new Vector3(INFRONT_BLUE_PENALTY_BOX_POSITION.x * arenaScaleX, INFRONT_BLUE_PENALTY_BOX_POSITION.y, INFRONT_BLUE_PENALTY_BOX_POSITION.z);
            INFRONT_RED_PENALTY_BOX_POSITION = new Vector3(INFRONT_RED_PENALTY_BOX_POSITION.x * arenaScaleX, INFRONT_RED_PENALTY_BOX_POSITION.y, INFRONT_RED_PENALTY_BOX_POSITION.z);

            DELAY_OF_GAME_POSITION = new Vector3(DELAY_OF_GAME_POSITION.x * arenaScaleX, DELAY_OF_GAME_POSITION.y, DELAY_OF_GAME_POSITION.z);

            DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1.x * arenaScaleX, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1.y, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1.z);
            DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2.x * arenaScaleX, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2.y, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2.z);

            DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_1.x * arenaScaleX, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_1.y, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_1.z);
            DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_2.x * arenaScaleX, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_2.y, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_2.z);

            DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_1.x * arenaScaleX, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_1.y, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_1.z);
            DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_2.x * arenaScaleX, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_2.y, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_2.z);

            DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_1.x * arenaScaleX, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_1.y, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_1.z);
            DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_2.x * arenaScaleX, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_2.y, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_2.z);

            DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1.x * arenaScaleX, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1.y, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1.z);
            DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2.x * arenaScaleX, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2.y, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2.z);

            DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_1.x * arenaScaleX, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_1.y, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_1.z);
            DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_2.x * arenaScaleX, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_2.y, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_2.z);

            DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_1.x * arenaScaleX, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_1.y, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_1.z);
            DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_2.x * arenaScaleX, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_2.y, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_2.z);

            DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_1.x * arenaScaleX, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_1.y, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_1.z);
            DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_2.x * arenaScaleX, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_2.y, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_2.z);
        }

        internal static void ScaleZCoordinates(float arenaScaleZ) {
            BLUE_PENALTY_BOX_POSITION = new Vector3(BLUE_PENALTY_BOX_POSITION.x, BLUE_PENALTY_BOX_POSITION.y, BLUE_PENALTY_BOX_POSITION.z * arenaScaleZ);
            RED_PENALTY_BOX_POSITION = new Vector3(RED_PENALTY_BOX_POSITION.x, RED_PENALTY_BOX_POSITION.y, RED_PENALTY_BOX_POSITION.z * arenaScaleZ);

            INFRONT_BLUE_PENALTY_BOX_POSITION = new Vector3(INFRONT_BLUE_PENALTY_BOX_POSITION.x, INFRONT_BLUE_PENALTY_BOX_POSITION.y, INFRONT_BLUE_PENALTY_BOX_POSITION.z * arenaScaleZ);
            INFRONT_RED_PENALTY_BOX_POSITION = new Vector3(INFRONT_RED_PENALTY_BOX_POSITION.x, INFRONT_RED_PENALTY_BOX_POSITION.y, INFRONT_RED_PENALTY_BOX_POSITION.z * arenaScaleZ);

            DELAY_OF_GAME_POSITION = new Vector3(DELAY_OF_GAME_POSITION.x, DELAY_OF_GAME_POSITION.y, DELAY_OF_GAME_POSITION.z * arenaScaleZ);

            DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1.x, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1.y, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1.z * arenaScaleZ);
            DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2.x, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2.y, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2.z * arenaScaleZ);

            DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_1.x, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_1.y, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_1.z * arenaScaleZ);
            DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_2.x, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_2.y, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_2.z * arenaScaleZ);

            DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_1.x, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_1.y, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_1.z * arenaScaleZ);
            DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_2.x, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_2.y, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_2.z * arenaScaleZ);

            DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_1.x, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_1.y, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_1.z * arenaScaleZ);
            DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_2.x, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_2.y, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_2.z * arenaScaleZ);

            DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1.x, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1.y, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1.z * arenaScaleZ);
            DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2.x, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2.y, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2.z * arenaScaleZ);

            DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_1.x, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_1.y, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_1.z * arenaScaleZ);
            DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_2.x, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_2.y, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_2.z * arenaScaleZ);

            DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_1.x, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_1.y, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_1.z * arenaScaleZ);
            DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_2.x, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_2.y, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_2.z * arenaScaleZ);

            DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_1.x, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_1.y, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_1.z * arenaScaleZ);
            DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_2.x, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_2.y, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_2.z * arenaScaleZ);
        }

        internal static void OffsetXCoordinates(float arenaOffsetX) {
            BLUE_PENALTY_BOX_POSITION = new Vector3(BLUE_PENALTY_BOX_POSITION.x + arenaOffsetX, BLUE_PENALTY_BOX_POSITION.y, BLUE_PENALTY_BOX_POSITION.z);
            RED_PENALTY_BOX_POSITION = new Vector3(RED_PENALTY_BOX_POSITION.x + arenaOffsetX, RED_PENALTY_BOX_POSITION.y, RED_PENALTY_BOX_POSITION.z);

            INFRONT_BLUE_PENALTY_BOX_POSITION = new Vector3(INFRONT_BLUE_PENALTY_BOX_POSITION.x + arenaOffsetX, INFRONT_BLUE_PENALTY_BOX_POSITION.y, INFRONT_BLUE_PENALTY_BOX_POSITION.z);
            INFRONT_RED_PENALTY_BOX_POSITION = new Vector3(INFRONT_RED_PENALTY_BOX_POSITION.x + arenaOffsetX, INFRONT_RED_PENALTY_BOX_POSITION.y, INFRONT_RED_PENALTY_BOX_POSITION.z);

            DELAY_OF_GAME_POSITION = new Vector3(DELAY_OF_GAME_POSITION.x + arenaOffsetX, DELAY_OF_GAME_POSITION.y, DELAY_OF_GAME_POSITION.z);

            DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1.x + arenaOffsetX, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1.y, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1.z);
            DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2.x + arenaOffsetX, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2.y, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2.z);

            DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_1.x + arenaOffsetX, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_1.y, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_1.z);
            DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_2.x + arenaOffsetX, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_2.y, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_2.z);

            DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_1.x + arenaOffsetX, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_1.y, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_1.z);
            DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_2.x + arenaOffsetX, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_2.y, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_2.z);

            DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_1.x + arenaOffsetX, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_1.y, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_1.z);
            DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_2.x + arenaOffsetX, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_2.y, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_2.z);

            DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1.x + arenaOffsetX, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1.y, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1.z);
            DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2.x + arenaOffsetX, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2.y, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2.z);

            DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_1.x + arenaOffsetX, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_1.y, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_1.z);
            DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_2.x + arenaOffsetX, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_2.y, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_2.z);

            DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_1.x + arenaOffsetX, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_1.y, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_1.z);
            DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_2.x + arenaOffsetX, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_2.y, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_2.z);

            DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_1.x + arenaOffsetX, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_1.y, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_1.z);
            DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_2.x + arenaOffsetX, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_2.y, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_2.z);
        }

        internal static void OffsetYCoordinates(float arenaOffsetY) {
            BLUE_PENALTY_BOX_POSITION = new Vector3(BLUE_PENALTY_BOX_POSITION.x, BLUE_PENALTY_BOX_POSITION.y + arenaOffsetY, BLUE_PENALTY_BOX_POSITION.z);
            RED_PENALTY_BOX_POSITION = new Vector3(RED_PENALTY_BOX_POSITION.x, RED_PENALTY_BOX_POSITION.y + arenaOffsetY, RED_PENALTY_BOX_POSITION.z);

            INFRONT_BLUE_PENALTY_BOX_POSITION = new Vector3(INFRONT_BLUE_PENALTY_BOX_POSITION.x, INFRONT_BLUE_PENALTY_BOX_POSITION.y + arenaOffsetY, INFRONT_BLUE_PENALTY_BOX_POSITION.z);
            INFRONT_RED_PENALTY_BOX_POSITION = new Vector3(INFRONT_RED_PENALTY_BOX_POSITION.x, INFRONT_RED_PENALTY_BOX_POSITION.y + arenaOffsetY, INFRONT_RED_PENALTY_BOX_POSITION.z);

            DELAY_OF_GAME_POSITION = new Vector3(DELAY_OF_GAME_POSITION.x, DELAY_OF_GAME_POSITION.y + arenaOffsetY, DELAY_OF_GAME_POSITION.z);

            DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1.x, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1.y + arenaOffsetY, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1.z);
            DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2.x, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2.y + arenaOffsetY, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2.z);

            DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_1.x, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_1.y + arenaOffsetY, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_1.z);
            DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_2.x, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_2.y + arenaOffsetY, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_2.z);

            DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_1.x, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_1.y + arenaOffsetY, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_1.z);
            DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_2.x, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_2.y + arenaOffsetY, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_2.z);

            DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_1.x, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_1.y + arenaOffsetY, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_1.z);
            DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_2.x, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_2.y + arenaOffsetY, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_2.z);

            DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1.x, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1.y + arenaOffsetY, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1.z);
            DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2.x, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2.y + arenaOffsetY, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2.z);

            DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_1.x, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_1.y + arenaOffsetY, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_1.z);
            DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_2.x, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_2.y + arenaOffsetY, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_2.z);

            DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_1.x, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_1.y + arenaOffsetY, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_1.z);
            DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_2.x, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_2.y + arenaOffsetY, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_2.z);

            DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_1.x, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_1.y + arenaOffsetY, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_1.z);
            DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_2.x, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_2.y + arenaOffsetY, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_2.z);
        }

        internal static void OffsetZCoordinates(float arenaOffsetZ) {
            BLUE_PENALTY_BOX_POSITION = new Vector3(BLUE_PENALTY_BOX_POSITION.x, BLUE_PENALTY_BOX_POSITION.y, BLUE_PENALTY_BOX_POSITION.z + arenaOffsetZ);
            RED_PENALTY_BOX_POSITION = new Vector3(RED_PENALTY_BOX_POSITION.x, RED_PENALTY_BOX_POSITION.y, RED_PENALTY_BOX_POSITION.z + arenaOffsetZ);

            INFRONT_BLUE_PENALTY_BOX_POSITION = new Vector3(INFRONT_BLUE_PENALTY_BOX_POSITION.x, INFRONT_BLUE_PENALTY_BOX_POSITION.y, INFRONT_BLUE_PENALTY_BOX_POSITION.z + arenaOffsetZ);
            INFRONT_RED_PENALTY_BOX_POSITION = new Vector3(INFRONT_RED_PENALTY_BOX_POSITION.x, INFRONT_RED_PENALTY_BOX_POSITION.y, INFRONT_RED_PENALTY_BOX_POSITION.z + arenaOffsetZ);

            DELAY_OF_GAME_POSITION = new Vector3(DELAY_OF_GAME_POSITION.x, DELAY_OF_GAME_POSITION.y, DELAY_OF_GAME_POSITION.z + arenaOffsetZ);

            DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1.x, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1.y, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1.z + arenaOffsetZ);
            DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2.x, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2.y, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2.z + arenaOffsetZ);

            DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_1.x, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_1.y, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_1.z + arenaOffsetZ);
            DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_2.x, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_2.y, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_2.z + arenaOffsetZ);

            DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_1.x, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_1.y, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_1.z + arenaOffsetZ);
            DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_2.x, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_2.y, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_2.z + arenaOffsetZ);

            DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_1.x, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_1.y, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_1.z + arenaOffsetZ);
            DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_2.x, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_2.y, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_2.z + arenaOffsetZ);

            DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1.x, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1.y, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1.z + arenaOffsetZ);
            DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2.x, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2.y, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2.z + arenaOffsetZ);

            DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_1.x, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_1.y, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_1.z + arenaOffsetZ);
            DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_2.x, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_2.y, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_2.z + arenaOffsetZ);

            DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_1.x, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_1.y, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_1.z + arenaOffsetZ);
            DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_2.x, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_2.y, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_2.z + arenaOffsetZ);

            DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_1 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_1.x, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_1.y, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_1.z + arenaOffsetZ);
            DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_2 = new Vector3(DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_2.x, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_2.y, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_2.z + arenaOffsetZ);
        }

        internal static bool PuckIsOutsideOfBounds(Puck puck) {
            if (Math.Abs(puck.Rigidbody.transform.position.x) > DELAY_OF_GAME_POSITION.x ||
                puck.Rigidbody.transform.position.y < DELAY_OF_GAME_POSITION.y ||
                Math.Abs(puck.Rigidbody.transform.position.z) > DELAY_OF_GAME_POSITION.z)
                return true;

            // Check for corners.
            if (puck.Rigidbody.transform.position.GetSideOfLine(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_1, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_1_POSITION_2) <= 0) // TOP RIGHT BLUE ZONE
                return true;

            if (puck.Rigidbody.transform.position.GetSideOfLine(DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_1, DELAY_OF_GAME_CORNER_TOP_RIGHT_LINE_2_POSITION_2) <= 0) // TOP RIGHT BLUE ZONE
                return true;

            if (puck.Rigidbody.transform.position.GetSideOfLine(DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_1, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_1_POSITION_2) >= 0) // TOP RIGHT BLUE ZONE
                return true;

            if (puck.Rigidbody.transform.position.GetSideOfLine(DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_1, DELAY_OF_GAME_CORNER_BOTTOM_RIGHT_LINE_2_POSITION_2) >= 0) // TOP RIGHT BLUE ZONE
                return true;

            if (puck.Rigidbody.transform.position.GetSideOfLine(DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_1, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_1_POSITION_2) >= 0) // TOP LEFT BLUE ZONE
                return true;

            if (puck.Rigidbody.transform.position.GetSideOfLine(DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_1, DELAY_OF_GAME_CORNER_TOP_LEFT_LINE_2_POSITION_2) >= 0) // TOP LEFT BLUE ZONE
                return true;

            if (puck.Rigidbody.transform.position.GetSideOfLine(DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_1, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_1_POSITION_2) <= 0) // TOP LEFT BLUE ZONE
                return true;

            if (puck.Rigidbody.transform.position.GetSideOfLine(DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_1, DELAY_OF_GAME_CORNER_BOTTOM_LEFT_LINE_2_POSITION_2) <= 0) // TOP LEFT BLUE ZONE
                return true;

            return false;
        }

        private static List<Penalty> GetAllPenalties() {
            return new List<Penalty>(PenalizedPlayers.SelectMany(x => x.Value));
        }

        internal static void ResetPenalties() {
            RemoveAllPenalties();

            PenalizedPlayers.Clear();
            PenalizedPlayersCountBlueTeam = 0;
            PenalizedPlayersInBoxCountBlueTeam = 0;
            PenalizedPlayersCountRedTeam = 0;
            PenalizedPlayersInBoxCountRedTeam = 0;

            PenaltyToBeCalled[PlayerTeam.Blue] = false;
            PenaltyToBeCalled[PlayerTeam.Red] = false;

            foreach (PlayerTeam key in new List<PlayerTeam>(PositionIsPenalized.Keys))
                PositionIsPenalized[key] = new LockDictionary<string, bool>(POSITION_IS_PENALIZED_DEFAULT);

            foreach (PlayerTeam key in new List<PlayerTeam>(PenaltyBenchPositionIsOccupied.Keys))
                PenaltyBenchPositionIsOccupied[key] = new LockDictionary<int, bool>(PENALTY_BENCH_POSITION_DEFAULT);

            Ruleset.PenaltyTimersElapsed.Clear();

            Ruleset.DataToSendToAll.Add(new List<string> { Codebase.Constants.REMOVED_ALL_PENALTIES_DATANAME, "1", Constants.FROM_SERVER_TO_CLIENT, });
            EventManager.TriggerEvent(Codebase.Constants.RULESET_MOD_NAME, new Dictionary<string, object> {
                { Codebase.Constants.REMOVED_ALL_PENALTIES_DATANAME, "1" },
            });

            UnpausePenalties();
        }

        internal static bool GivePenalty(PenaltyType penaltyType, Player penalizedPlayer, string receivingPlayerSteamId = "", Player referee = null) {
            if (referee == null) {
                if (!Ruleset.ServerConfig.Penalty.Interference && (penaltyType == PenaltyType.Interference || penaltyType == PenaltyType.Tripping))
                    return false;
                if (!Ruleset.ServerConfig.Penalty.GoalieInterference && penaltyType == PenaltyType.GoalieInterference)
                    return false;
                if (!Ruleset.ServerConfig.Penalty.DelayOfGame && penaltyType == PenaltyType.DelayOfGame)
                    return false;
                if (!Ruleset.ServerConfig.Penalty.FaceoffViolation && penaltyType == PenaltyType.FaceoffViolation)
                    return false;
                if (!Ruleset.ServerConfig.Penalty.Embellishment && penaltyType == PenaltyType.Embellishment)
                    return false;
                if (!Ruleset.ServerConfig.Penalty.Roughing && penaltyType == PenaltyType.Roughing)
                    return false;
                if (!Ruleset.ServerConfig.Penalty.Charging && penaltyType == PenaltyType.Charging)
                    return false;
            }

            List<Player> teamPlayers = PlayerManager.Instance.GetPlayersByTeam(penalizedPlayer.Team).Where(x => !Codebase.PlayerFunc.IsGoalie(x)).ToList();

            if (teamPlayers.Count < Ruleset.ServerConfig.Penalty.MaximumPenaltyImmunedPlayersCountPerTeam)
                return false;

            string penalizedPlayerSteamId;

            try {
                penalizedPlayerSteamId = penalizedPlayer.SteamId.Value.ToString();
                if (string.IsNullOrEmpty(penalizedPlayerSteamId))
                    return false;
            }
            catch (Exception ex) {
                Logging.LogError($"Error in {nameof(GivePenalty)} 1.\n{ex}", Ruleset.ServerConfig);
                return false;
            }

            if (!PenalizedPlayers.TryGetValue(penalizedPlayerSteamId, out LockList<Penalty> penaltyList)) {
                penaltyList = new LockList<Penalty>();
                PenalizedPlayers.Add(penalizedPlayerSteamId, penaltyList);
            }

            if (penaltyList.Count == Ruleset.ServerConfig.Penalty.MaxPenaltiesCountPerPlayer)
                return false;

            DateTime now = DateTime.UtcNow;
            if (!string.IsNullOrEmpty(receivingPlayerSteamId)) {
                List<Penalty> allPenalties = GetAllPenalties();
                if (allPenalties.Where(x => x.Team == penalizedPlayer.Team && x.PenaltyType == penaltyType && x.ReceivingPlayerSteamId == receivingPlayerSteamId).Any(x => (x.PenaltyDateTime - now).TotalMilliseconds < 4000)) // TODO : Config.
                    return false;

                if ((penaltyType == PenaltyType.Interference || penaltyType == PenaltyType.GoalieInterference) && allPenalties.Where(x => x.Team == penalizedPlayer.Team && (x.PenaltyType == PenaltyType.Charging) && x.ReceivingPlayerSteamId == receivingPlayerSteamId).Any(x => (x.PenaltyDateTime - now).TotalMilliseconds < 4000)) // TODO : Config.
                    return false;

                if (penaltyType == PenaltyType.Roughing && allPenalties.Where(x => x.Team == penalizedPlayer.Team && (x.PenaltyType == PenaltyType.Interference || x.PenaltyType == PenaltyType.GoalieInterference || x.PenaltyType == PenaltyType.Charging) && x.ReceivingPlayerSteamId == receivingPlayerSteamId).Any(x => (x.PenaltyDateTime - now).TotalMilliseconds < 4000)) // TODO : Config.
                    return false;
            }

            if ((penalizedPlayer.Team == PlayerTeam.Blue && PenalizedPlayersCountBlueTeam == Ruleset.ServerConfig.Penalty.MaxPenalizedPlayersPerTeam) ||
                (penalizedPlayer.Team == PlayerTeam.Red && PenalizedPlayersCountRedTeam == Ruleset.ServerConfig.Penalty.MaxPenalizedPlayersPerTeam) ||
                (teamPlayers.Count(x => !PenalizedPlayers.TryGetValue(x.SteamId.Value.ToString(), out LockList<Penalty> penalties) || penalties.Count == 0) < Ruleset.ServerConfig.Penalty.MaximumPenaltyImmunedPlayersCountPerTeam)) {
                bool unpenalizeOnePlayer = false;
                if (penalizedPlayer.Team == PlayerTeam.Blue) {
                    if (PenalizedPlayersCountBlueTeam != 0)
                        unpenalizeOnePlayer = true;
                }
                else if (penalizedPlayer.Team == PlayerTeam.Red) {
                    if (PenalizedPlayersCountRedTeam != 0)
                        unpenalizeOnePlayer = true;
                }

                if (!unpenalizeOnePlayer)
                    return false;

                var _penaltiesLINQ = PenalizedPlayers.Where(x => x.Value.Count == 1 && x.Value.First().Team == penalizedPlayer.Team).OrderBy(x => x.Value.Min(y => y.Timer.MillisecondsLeft));
                if (!_penaltiesLINQ.Any())
                    return false;

                KeyValuePair<string, LockList<Penalty>> _penalties = _penaltiesLINQ.First();

                var _playerToUnpenalizeLINQ = teamPlayers.Where(x => x.SteamId.Value.ToString() == _penalties.Key);
                if (!_playerToUnpenalizeLINQ.Any())
                    return false;

                Player _playerToUnpenalize = _playerToUnpenalizeLINQ.First();
                if (_playerToUnpenalize == null || !_playerToUnpenalize)
                    return false;

                if (_penalties.Value.First().Timer.MillisecondsLeft > GetPenaltyTypeTime(penaltyType))
                    return false;

                RemoveOnePenalty(_playerToUnpenalize.Team, true);
            }

            // If goalie has a penalty, take another player.
            if (Codebase.PlayerFunc.IsGoalie(penalizedPlayer) || penalizedPlayer.PlayerPosition.Name == Codebase.PlayerFunc.GOALIE_POSITION) {
                List<Player> possiblePlayersToPenalize = new List<Player>();
                foreach (Player teamPlayer in teamPlayers) {
                    if (!Codebase.PlayerFunc.IsPlayerPlaying(teamPlayer))
                        continue;

                    if (PenalizedPlayers.TryGetValue(teamPlayer.SteamId.Value.ToString(), out LockList<Penalty> __penaltyList)) {
                        if (__penaltyList.Count != 0)
                            continue;
                    }

                    possiblePlayersToPenalize.Add(teamPlayer);
                }

                if (possiblePlayersToPenalize.Count == 0)
                    return false;

                penalizedPlayer = possiblePlayersToPenalize.OrderBy(x => x.Goals.Value + x.Assists.Value).First();
                penalizedPlayerSteamId = penalizedPlayer.SteamId.Value.ToString();

                if (!PenalizedPlayers.TryGetValue(penalizedPlayerSteamId, out LockList<Penalty> _penaltyList)) {
                    _penaltyList = new LockList<Penalty>();
                    PenalizedPlayers.Add(penalizedPlayerSteamId, _penaltyList);
                }
                penaltyList = _penaltyList;
            }

            PositionIsPenalized[penalizedPlayer.Team][penalizedPlayer.PlayerPosition.Name] = true;
            PenaltyToBeCalled[penalizedPlayer.Team] = true;
            if (penaltyList.Count == 0) {
                if (penalizedPlayer.Team == PlayerTeam.Blue)
                    PenalizedPlayersCountBlueTeam++;
                else
                    PenalizedPlayersCountRedTeam++;
            }

            LastPenaltyCalled = penaltyType;

            Penalty newPenalty = new Penalty(
                penalizedPlayerSteamId,
                penalizedPlayer.Team,
                penalizedPlayer.Number.Value.ToString(),
                penalizedPlayer.Username.Value.ToString(),
                penaltyType,
                penalizedPlayer.PlayerPosition.Name,
                receivingPlayerSteamId
            );
            penaltyList.Add(newPenalty);

            int penaltyTimeMilliseconds = GetPenaltyTypeTime(penaltyType);

            string message = $"Penalty #{penalizedPlayer.Number.Value} {penalizedPlayer.Username.Value}, {penaltyTimeMilliseconds / 1000} seconds for {penaltyType.GetDescription("ToString")}";
            if (!string.IsNullOrEmpty(receivingPlayerSteamId)) {
                Player receivingPlayer = PlayerManager.Instance.GetPlayerBySteamId(receivingPlayerSteamId);
                if (Codebase.PlayerFunc.IsPlayerPlaying(receivingPlayer))
                    message += $" on #{receivingPlayer.Number.Value} {receivingPlayer.Username.Value}";
            }

            if (referee != null)
                message += $", called by #{referee.Number.Value} {referee.Username.Value}";

            Ruleset.SystemChatMessages.Add(message);
            Logging.Log(message, Ruleset.ServerConfig);

            // TODO : Get actual ref signal.
            Ruleset.DataToSendToAll.Add(new List<string> { RefSignals.GetSignalConstant(true, penalizedPlayer.Team), RefSignals.HIGHSTICK_LINESMAN, Constants.FROM_SERVER_TO_CLIENT, });
            Ruleset.DataToSendToAll.Add(new List<string> { Codebase.Constants.PENALIZED_PLAYER_PENDING_DATANAME, penalizedPlayerSteamId, Constants.FROM_SERVER_TO_CLIENT, });
            EventManager.TriggerEvent(Codebase.Constants.RULESET_MOD_NAME, new Dictionary<string, object> {
                { Codebase.Constants.PENALIZED_PLAYER_PENDING_DATANAME, penalizedPlayerSteamId },
                { "pim", penaltyTimeMilliseconds },
            });

            if (PenaltyToBeCalled.Values.All(x => x))
                Ruleset.CallPenalty(PlayerTeam.None);

            return true;
        }

        internal static void StartPenalties() {
            PenaltyToBeCalled[PlayerTeam.Blue] = false;
            PenaltyToBeCalled[PlayerTeam.Red] = false;

            PenalizedPlayersInBoxCountBlueTeam = PenalizedPlayersCountBlueTeam;
            PenalizedPlayersInBoxCountRedTeam = PenalizedPlayersCountRedTeam;

            foreach (LockList<Penalty> penalties in PenalizedPlayers.Values) {
                // Player to the box and start first penalty.
                if (penalties.Count != 0 && penalties.All(x => !x.CurrentPenalty)) {
                    Penalty firstPenalty = penalties.First();
                    firstPenalty.CurrentPenalty = true;

                    Player penalizedPlayer = PlayerManager.Instance.GetPlayerBySteamId(firstPenalty.SteamId);
                    if (penalizedPlayer == null || !penalizedPlayer || !penalizedPlayer.IsCharacterSpawned)
                        return;

                    TeleportPlayer(penalizedPlayer);
                }
            }
        }

        internal static void AddTimeToAllPenalties(long milliseconds) {
            foreach (Penalty penalty in GetAllPenalties())
                penalty.Timer.AddTime(milliseconds);
        }

        internal static void TeleportPlayers() {
            foreach (PlayerTeam key in new List<PlayerTeam>(PenaltyBenchPositionIsOccupied.Keys))
                PenaltyBenchPositionIsOccupied[key] = new LockDictionary<int, bool>(PENALTY_BENCH_POSITION_DEFAULT);

            foreach (LockList<Penalty> penalties in PenalizedPlayers.Values) {
                // Player to the box and start first penalty.
                if (penalties.Any(x => x.CurrentPenalty)) {
                    TeleportPlayer(penalties.First().SteamId);
                }
            }
        }

        internal static void TeleportPlayer(string playerSteamId) {
            Player player = PlayerManager.Instance.GetPlayerBySteamId(playerSteamId);
            if (player == null || !player || !player.IsCharacterSpawned)
                return;

            TeleportPlayer(player);
        }

        internal static void TeleportPlayer(Player player) {
            if (player.IsCharacterSpawned) {
                player.PlayerBody.Rigidbody.linearVelocity = Vector3.zero;
                player.PlayerBody.Rigidbody.angularVelocity = Vector3.zero;
            }

            player.PlayerBody.Rigidbody.constraints = RigidbodyConstraints.FreezeAll;

            Vector3 penaltyBoxPosition;
            float zOffset = 0;

            if (!PenaltyBenchPositionIsOccupied[player.Team][0])
                PenaltyBenchPositionIsOccupied[player.Team][0] = true;
            else if (!PenaltyBenchPositionIsOccupied[player.Team][1]) {
                PenaltyBenchPositionIsOccupied[player.Team][1] = true;
                zOffset = 1.5f;
            }
            else if (!PenaltyBenchPositionIsOccupied[player.Team][2]) {
                PenaltyBenchPositionIsOccupied[player.Team][2] = true;
                zOffset = 3f;
            }

            if (player.Team == PlayerTeam.Blue)
                penaltyBoxPosition = new Vector3(BLUE_PENALTY_BOX_POSITION.x, BLUE_PENALTY_BOX_POSITION.y, BLUE_PENALTY_BOX_POSITION.z + zOffset);
            else
                penaltyBoxPosition = new Vector3(RED_PENALTY_BOX_POSITION.x, RED_PENALTY_BOX_POSITION.y, RED_PENALTY_BOX_POSITION.z - zOffset);

            player.PlayerBody.Server_Teleport(penaltyBoxPosition, PENALTY_ROTATION);
            Ruleset.PlayersToTeleport.Add(new PlayerWithCoordinate { Player = player, Position = penaltyBoxPosition, Rotation = PENALTY_ROTATION, });
        }

        internal static void PausePenalties() {
            foreach (Penalty penalty in GetAllPenalties()) {
                if (penalty.CurrentPenalty)
                    penalty.Timer.Pause();
            }

            foreach (PlayerTeam key in new List<PlayerTeam>(PenaltyBenchPositionIsOccupied.Keys))
                PenaltyBenchPositionIsOccupied[key] = new LockDictionary<int, bool>(PENALTY_BENCH_POSITION_DEFAULT);

            Ruleset.DataToSendToAll.Add(new List<string> { Codebase.Constants.PENALTIES_PAUSED_DATANAME, "1", Constants.FROM_SERVER_TO_CLIENT, });
            EventManager.TriggerEvent(Codebase.Constants.RULESET_MOD_NAME, new Dictionary<string, object> {
                { Codebase.Constants.PENALTIES_PAUSED_DATANAME, "1" },
            });
        }

        internal static void UnpausePenalties() {
            string penaltyUIMsg = "";
            List<string> allPenaltiesSteamId = new List<string>();
            string allPenaltiesSteamIdString = "";

            foreach (Penalty penalty in GetAllPenalties()) {
                if (penalty.Timer.TimerEnded())
                    continue;

                if (penalty.CurrentPenalty)
                    penalty.Timer.Start();

                penaltyUIMsg = $"{penaltyUIMsg}{(penalty.Team == PlayerTeam.Blue ? "B" : "R")} {penalty.Position} #{penalty.PlayerNumber}!{penalty.Timer.MillisecondsLeft}!{(penalty.CurrentPenalty ? "1" : "0")};";

                allPenaltiesSteamId.Add(penalty.SteamId);
                allPenaltiesSteamIdString = $"{allPenaltiesSteamIdString}{penalty.SteamId};";
            }

            if (string.IsNullOrEmpty(penaltyUIMsg)) {
                Ruleset.DataToSendToAll.Add(new List<string> { Codebase.Constants.REMOVED_ALL_PENALTIES_DATANAME, "1", Constants.FROM_SERVER_TO_CLIENT, });
                return;
            }

            penaltyUIMsg = penaltyUIMsg.Remove(penaltyUIMsg.Length - 1);
            Ruleset.DataToSendToAll.Add(new List<string> { Codebase.Constants.PENALTIES_UNPAUSED_DATANAME, penaltyUIMsg, Constants.FROM_SERVER_TO_CLIENT, });

            allPenaltiesSteamIdString = allPenaltiesSteamIdString.Remove(allPenaltiesSteamIdString.Length - 1);
            Ruleset.DataToSendToAll.Add(new List<string> { Codebase.Constants.PENALIZED_PLAYERS_DATANAME, allPenaltiesSteamIdString, Constants.FROM_SERVER_TO_CLIENT, });
            EventManager.TriggerEvent(Codebase.Constants.RULESET_MOD_NAME, new Dictionary<string, object> {
                { Codebase.Constants.PENALIZED_PLAYERS_DATANAME, allPenaltiesSteamId },
            });
        }

        internal static void UnpenalizePlayer(string penalizedPlayerSteamId, PlayerTeam penalizedPlayerTeam, string penalizedPlayerPosition) {
            PositionIsPenalized[penalizedPlayerTeam][penalizedPlayerPosition] = false;

            if (penalizedPlayerTeam == PlayerTeam.Blue) {
                PenalizedPlayersCountBlueTeam--;
                PenalizedPlayersInBoxCountBlueTeam--;

                if (PenalizedPlayersInBoxCountBlueTeam < 0)
                    PenalizedPlayersInBoxCountBlueTeam = 0;
            }
            else {
                PenalizedPlayersCountRedTeam--;
                PenalizedPlayersInBoxCountRedTeam--;

                if (PenalizedPlayersInBoxCountRedTeam < 0)
                    PenalizedPlayersInBoxCountRedTeam = 0;
            }

            Player penalizedPlayer = PlayerManager.Instance.GetPlayerBySteamId(penalizedPlayerSteamId);
            if (penalizedPlayer != null && penalizedPlayer && penalizedPlayer.IsCharacterSpawned) {
                if (penalizedPlayerTeam == PlayerTeam.Blue) {
                    penalizedPlayer.PlayerBody.Server_Teleport(INFRONT_BLUE_PENALTY_BOX_POSITION, PENALTY_ROTATION);
                    Ruleset.PlayersToTeleport.Add(new PlayerWithCoordinate { Player = penalizedPlayer, Position = INFRONT_BLUE_PENALTY_BOX_POSITION, Rotation = PENALTY_ROTATION, });
                }
                else {
                    penalizedPlayer.PlayerBody.Server_Teleport(INFRONT_RED_PENALTY_BOX_POSITION, PENALTY_ROTATION);
                    Ruleset.PlayersToTeleport.Add(new PlayerWithCoordinate { Player = penalizedPlayer, Position = INFRONT_RED_PENALTY_BOX_POSITION, Rotation = PENALTY_ROTATION, });
                }

                penalizedPlayer.PlayerBody.Server_Unfreeze();
                Ruleset.SystemChatMessages.Add($"#{penalizedPlayer.Number.Value} {penalizedPlayer.Username.Value} UNPENALIZED");
                Logging.Log($"#{penalizedPlayer.Number.Value} {penalizedPlayer.Username.Value} UNPENALIZED", Ruleset.ServerConfig);
            }

            Ruleset.DataToSendToAll.Add(new List<string> { Codebase.Constants.UNPENALIZED_PLAYER_DATANAME, penalizedPlayerSteamId, Constants.FROM_SERVER_TO_CLIENT, });
            EventManager.TriggerEvent(Codebase.Constants.RULESET_MOD_NAME, new Dictionary<string, object> {
                { Codebase.Constants.UNPENALIZED_PLAYER_DATANAME, penalizedPlayerSteamId },
            });
        }

        internal static void RemoveAllPenalties() {
            List<Penalty> penaltiesToRemove = GetAllPenalties();
            if (penaltiesToRemove.Count == 0)
                return;
            foreach (Penalty penaltyToRemove in penaltiesToRemove) {
                if (penaltyToRemove == null || penaltyToRemove.Equals(default(Penalty)))
                    continue;

                penaltyToRemove.Timer.Pause();
                penaltyToRemove.Timer.TimerCallback(null);
            }
        }

        internal static bool RemoveOnePenalty(PlayerTeam penalizedPlayerTeam, bool removePendingPenalty = false) {
            if (penalizedPlayerTeam == PlayerTeam.Blue) {
                if (removePendingPenalty) {
                    if (PenalizedPlayersCountBlueTeam == 0)
                        return false;
                }
                else {
                    if (PenalizedPlayersInBoxCountBlueTeam == 0)
                        return false;
                }
            }
            else if (penalizedPlayerTeam == PlayerTeam.Red) {
                if (removePendingPenalty) {
                    if (PenalizedPlayersCountRedTeam == 0)
                        return false;
                }
                else {
                    if (PenalizedPlayersInBoxCountRedTeam == 0)
                        return false;
                }
            }

            Penalty penaltyToRemove = GetAllPenalties().Where(x => x.Team == penalizedPlayerTeam).OrderBy(x => x.Timer.MillisecondsLeft).FirstOrDefault();
            if (penaltyToRemove == null || penaltyToRemove.Equals(default(Penalty)))
                return false;

            penaltyToRemove.Timer.Pause();
            penaltyToRemove.Timer.TimerCallback(null);

            return true;
        }

        internal static string FakePlayerPositionForFaceoffByAvailability(string position, PlayerTeam team, List<(string Position, bool IsPenalized)> claimedPositions) {
            if (team == PlayerTeam.Blue && PenalizedPlayersCountBlueTeam == 0)
                return position;

            if (team == PlayerTeam.Red && PenalizedPlayersCountRedTeam == 0)
                return position;

            switch (position) {
                case Codebase.PlayerFunc.RIGHT_WINGER_POSITION:
                    if (!claimedPositions.Any(x => !x.IsPenalized && x.Position == Codebase.PlayerFunc.LEFT_WINGER_POSITION))
                        return Codebase.PlayerFunc.LEFT_WINGER_POSITION;
                    break;

                case Codebase.PlayerFunc.LEFT_DEFENDER_POSITION:
                    if (!claimedPositions.Any(x => !x.IsPenalized && x.Position == Codebase.PlayerFunc.LEFT_WINGER_POSITION) && !claimedPositions.Any(x => !x.IsPenalized && x.Position == Codebase.PlayerFunc.RIGHT_WINGER_POSITION))
                        return Codebase.PlayerFunc.LEFT_WINGER_POSITION;

                    if (!claimedPositions.Any(x => !x.IsPenalized && x.Position == Codebase.PlayerFunc.RIGHT_WINGER_POSITION))
                        return Codebase.PlayerFunc.RIGHT_WINGER_POSITION;
                    break;

                case Codebase.PlayerFunc.RIGHT_DEFENDER_POSITION:
                    if (!claimedPositions.Any(x => !x.IsPenalized && x.Position == Codebase.PlayerFunc.LEFT_WINGER_POSITION) && !claimedPositions.Any(x => !x.IsPenalized && x.Position == Codebase.PlayerFunc.RIGHT_WINGER_POSITION) && !claimedPositions.Any(x => !x.IsPenalized && x.Position == Codebase.PlayerFunc.LEFT_DEFENDER_POSITION))
                        return Codebase.PlayerFunc.LEFT_WINGER_POSITION;

                    if (!claimedPositions.Any(x => !x.IsPenalized && x.Position == Codebase.PlayerFunc.RIGHT_WINGER_POSITION) && !claimedPositions.Any(x => !x.IsPenalized && x.Position == Codebase.PlayerFunc.LEFT_DEFENDER_POSITION))
                        return Codebase.PlayerFunc.RIGHT_WINGER_POSITION;

                    if (!claimedPositions.Any(x => !x.IsPenalized && x.Position == Codebase.PlayerFunc.LEFT_DEFENDER_POSITION))
                        return Codebase.PlayerFunc.LEFT_DEFENDER_POSITION;
                    break;
            }

            return position;
        }

        internal static string GetPlayerPositionForFaceoff(string position, PlayerTeam team, FaceoffSpot faceoffSpot, List<(string Position, bool IsPenalized)> claimedPositions) {
            position = FakePlayerPositionForFaceoffByAvailability(position, team, claimedPositions);

            bool centerPositionIsOpen = PositionIsPenalized[team][Codebase.PlayerFunc.CENTER_POSITION] && !claimedPositions.Any(x => !x.IsPenalized && x.Position == Codebase.PlayerFunc.CENTER_POSITION);
            bool leftDefenderPositionIsOpen = PositionIsPenalized[team][Codebase.PlayerFunc.LEFT_DEFENDER_POSITION] && !claimedPositions.Any(x => !x.IsPenalized && x.Position == Codebase.PlayerFunc.LEFT_DEFENDER_POSITION);

            switch (position) {
                case Codebase.PlayerFunc.LEFT_WINGER_POSITION:
                    if (centerPositionIsOpen)
                        return Codebase.PlayerFunc.CENTER_POSITION;
                    if (leftDefenderPositionIsOpen)
                        return Codebase.PlayerFunc.LEFT_DEFENDER_POSITION;
                    break;

                case Codebase.PlayerFunc.RIGHT_WINGER_POSITION:
                    bool leftWingerPositionIsOpen = PositionIsPenalized[team][Codebase.PlayerFunc.LEFT_WINGER_POSITION] && !claimedPositions.Any(x => !x.IsPenalized && x.Position == Codebase.PlayerFunc.LEFT_WINGER_POSITION);

                    if (centerPositionIsOpen && leftWingerPositionIsOpen)
                        return Codebase.PlayerFunc.CENTER_POSITION;

                    if (team == PlayerTeam.Blue) {
                        if (centerPositionIsOpen && (faceoffSpot == FaceoffSpot.BlueteamBLLeft || faceoffSpot == FaceoffSpot.RedteamBLLeft || faceoffSpot == FaceoffSpot.BlueteamDZoneLeft || faceoffSpot == FaceoffSpot.RedteamDZoneLeft || faceoffSpot == FaceoffSpot.Center))
                            return Codebase.PlayerFunc.LEFT_WINGER_POSITION;
                    }
                    else {
                        if (centerPositionIsOpen && (faceoffSpot == FaceoffSpot.BlueteamBLRight || faceoffSpot == FaceoffSpot.RedteamBLRight || faceoffSpot == FaceoffSpot.BlueteamDZoneRight || faceoffSpot == FaceoffSpot.RedteamDZoneRight || faceoffSpot == FaceoffSpot.Center))
                            return Codebase.PlayerFunc.LEFT_WINGER_POSITION;
                    }

                    bool rightDefenderPositionIsOpen = PositionIsPenalized[team][Codebase.PlayerFunc.RIGHT_DEFENDER_POSITION] && !claimedPositions.Any(x => !x.IsPenalized && x.Position == Codebase.PlayerFunc.RIGHT_DEFENDER_POSITION);

                    if (rightDefenderPositionIsOpen)
                        return Codebase.PlayerFunc.RIGHT_DEFENDER_POSITION;
                    if (centerPositionIsOpen && leftDefenderPositionIsOpen)
                        return Codebase.PlayerFunc.LEFT_DEFENDER_POSITION;
                    break;
            }

            return position;
        }

        internal static int GetPenaltyTypeTime(PenaltyType penaltyType) {
            switch (penaltyType) {
                case PenaltyType.Interference:
                case PenaltyType.Tripping:
                    return Ruleset.ServerConfig.Penalty.InterferenceTime;

                case PenaltyType.GoalieInterference:
                    return Ruleset.ServerConfig.Penalty.GoalieInterferenceTime;

                case PenaltyType.DelayOfGame:
                    return Ruleset.ServerConfig.Penalty.DelayOfGameTime;

                case PenaltyType.FaceoffViolation:
                    return Ruleset.ServerConfig.Penalty.FaceoffViolationTime;

                case PenaltyType.Embellishment:
                    return Ruleset.ServerConfig.Penalty.EmbellishmentTime;

                case PenaltyType.Roughing:
                    return Ruleset.ServerConfig.Penalty.RoughingTime;

                case PenaltyType.Charging:
                    return Ruleset.ServerConfig.Penalty.ChargingTime;
            }

            return PenaltyModule.LONG_PENALTY_TIME_MS;
        }
        #endregion
    }

    internal class Penalty {
        internal string SteamId { get; }

        internal PenaltyType PenaltyType { get; }

        internal PausableTimer Timer { get; set; }

        internal bool CurrentPenalty { get; set; }

        internal DateTime PenaltyDateTime { get; set; }

        internal PlayerTeam Team { get; set; }

        internal string Position { get; set; }

        internal string PlayerNumber { get; set; }

        internal string PlayerUsername { get; set; }

        internal string ReceivingPlayerSteamId { get; set; }

        internal Penalty(string steamId, PlayerTeam team, string playerNumber, string playerUsername, PenaltyType penaltyType, string position, string receivingPlayerSteamId) {
            SteamId = steamId;
            Team = team;
            PlayerNumber = playerNumber;
            PlayerUsername = playerUsername;
            PenaltyType = penaltyType;
            Position = position;
            CurrentPenalty = false;
            ReceivingPlayerSteamId = receivingPlayerSteamId;

            SetTimer();

            PenaltyDateTime = DateTime.UtcNow;
        }

        internal void SetTimer() {
            Timer = new PausableTimer(PenaltyTimer_Elapsed, PenaltyModule.GetPenaltyTypeTime(PenaltyType));
        }

        private void PenaltyTimer_Elapsed() {
            try {
                if (!PenaltyModule.PenalizedPlayers.ContainsKey(SteamId))
                    return;

                Ruleset.PenaltyTimersElapsed.Add(this);
            }
            catch (Exception ex) {
                Logging.LogError($"Error in {nameof(PenaltyTimer_Elapsed)}.\n{ex}", Ruleset.ServerConfig);
            }
        }

        internal static void PenaltyTimer_Action(Penalty penaltyToRemove) {
            try {
                if (penaltyToRemove == null)
                    return;

                PenaltyModule.PenalizedPlayers[penaltyToRemove.SteamId].Remove(penaltyToRemove);

                string penaltyOverMsg = $"PENALTY #{penaltyToRemove.PlayerNumber} {penaltyToRemove.PlayerUsername} OVER";
                Ruleset.SystemChatMessages.Add(penaltyOverMsg);
                Logging.Log(penaltyOverMsg, Ruleset.ServerConfig);

                // Unpenalize player if no more penalties or start the next one.
                if (PenaltyModule.PenalizedPlayers[penaltyToRemove.SteamId].Count == 0)
                    PenaltyModule.UnpenalizePlayer(penaltyToRemove.SteamId, penaltyToRemove.Team, penaltyToRemove.Position);
                else {
                    Penalty firstPenalty = PenaltyModule.PenalizedPlayers[penaltyToRemove.SteamId].First();
                    firstPenalty.CurrentPenalty = true;
                }

                PenaltyModule.UnpausePenalties();
                if (GameManager.Instance.Phase != GamePhase.Play)
                    PenaltyModule.PausePenalties();
            }
            catch (Exception ex) {
                Logging.LogError($"Error in {nameof(PenaltyTimer_Action)}.\n{ex}", Ruleset.ServerConfig);
            }
        }
    }

    public enum PenaltyType {
        Interference,
        [Description("Goalie interference"), Category("ToString")]
        GoalieInterference,
        [Description("Delay of game"), Category("ToString")]
        DelayOfGame,
        Tripping,
        Embellishment,
        [Description("Faceoff violation"), Category("ToString")]
        FaceoffViolation,
        Roughing,
        Charging,
    }
}
